// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuW5R1n6WOnocLsZzxJBC_z1a-J4GID5s',
    appId: '1:560705657428:web:e9a8e9a29203b9001cabc1',
    messagingSenderId: '560705657428',
    projectId: 'authphone-a77ae',
    authDomain: 'authphone-a77ae.firebaseapp.com',
    storageBucket: 'authphone-a77ae.appspot.com',
    measurementId: 'G-YZ760T97EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv24eV6Bxy8UfDQqtz1Bpa8pEyW42GZ38',
    appId: '1:560705657428:android:c42e571abd4fde5e1cabc1',
    messagingSenderId: '560705657428',
    projectId: 'authphone-a77ae',
    storageBucket: 'authphone-a77ae.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuW5R1n6WOnocLsZzxJBC_z1a-J4GID5s',
    appId: '1:560705657428:web:1b54328b5bf930731cabc1',
    messagingSenderId: '560705657428',
    projectId: 'authphone-a77ae',
    authDomain: 'authphone-a77ae.firebaseapp.com',
    storageBucket: 'authphone-a77ae.appspot.com',
    measurementId: 'G-FRGBZ3F3F6',
  );
}